Repository exoscale/cli, pull requests merged in 2018-10, with the labels that each got.

#6 jenkins: use golangci
  .golangci.yml
  .gometalinter.json
  Jenkinsfile
  cmd/privnet.go
  cmd/template.go
  cmd/vm_create.go
  doc/main.go
Labels: good first issue

#20 api: add missing vm-group calls
  cmd/api_layout.go
Labels: enhancement

#28 vm: show breaks on non-UUID content
  go.mod
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/README.md
  vendor/github.com/exoscale/egoscale/nics.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/github.com/exoscale/egoscale/virtual_machines.go
  vendor/modules.txt
Labels: bug

#22 Account flag overwritten in exo api
  cmd/root.go
Labels: HOLD :hand:, WIP :construction:
