Repository exoscale/cli, pull requests merged in 2019-01, with the labels that each got.

#58 Add Runstat.us
  cmd/config.go
  cmd/root.go
  cmd/runstatus.go
  cmd/runstatus_create.go
  cmd/runstatus_delete.go
  cmd/runstatus_incident.go
  cmd/runstatus_incident_add.go
  cmd/runstatus_incident_list.go
  cmd/runstatus_incident_remove.go
  cmd/runstatus_incident_show.go
  cmd/runstatus_incident_update.go
  cmd/runstatus_list.go
  cmd/runstatus_maintenance.go
  cmd/runstatus_maintenance_add.go
  cmd/runstatus_maintenance_list.go
  cmd/runstatus_maintenance_remove.go
  cmd/runstatus_maintenance_show.go
  cmd/runstatus_maintenance_update.go
  cmd/runstatus_service.go
  cmd/runstatus_service_create.go
  cmd/runstatus_service_delete.go
  cmd/runstatus_service_list.go
  cmd/runstatus_service_show.go
  go.mod
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/runstatus.go
  vendor/github.com/exoscale/egoscale/runstatus_event.go
  vendor/github.com/exoscale/egoscale/runstatus_incident.go
  vendor/github.com/exoscale/egoscale/runstatus_maintenance.go
  vendor/github.com/exoscale/egoscale/runstatus_service.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/key.go
  vendor/github.com/go-ini/ini/section.go
  vendor/modules.txt
Labels: enhancement

#85 firewall: fix --my-ip and flagless add
  CHANGELOG.md
  cmd/firewall_add.go
  cmd/firewall_remove.go
Labels: bug

#91 firewall: fix ping6 protocol name
  cmd/firewall_add.go
Labels: bug

#87 exo sshkey delete --all
  cmd/sshkey_delete.go
Labels: enhancement

#79 Add list iso on exo vm template list
  cmd/template_list.go
Labels: HOLD :hand:
